mv lqp20.graph.json lqp22.graph.json
mv lqp19.graph.json lqp21.graph.json
mv lqp18.graph.json lqp20.graph.json
mv lqp17.graph.json lqp19.graph.json
mv lqp16.graph.json lqp18.graph.json
mv lqp15.graph.json lqp17.graph.json
mv lqp14.graph.json lqp16.graph.json
mv lqp13.graph.json lqp14.graph.json
mv lqp12.graph.json lqp13.graph.json
mv lqp11.graph.json lqp12.graph.json
mv lqp10.graph.json lqp11.graph.json
mv lqp9.graph.json lqp10.graph.json
mv lqp8.graph.json lqp9.graph.json
mv lqp7.graph.json lqp8.graph.json
mv lqp6.graph.json lqp7.graph.json
mv lqp5.graph.json lqp6.graph.json
mv lqp4.graph.json lqp5.graph.json
mv lqp3.graph.json lqp4.graph.json
mv lqp2.graph.json lqp3.graph.json
mv lqp1.graph.json lqp2.graph.json
mv lqp0.graph.json lqp1.graph.json