mv pqp20.graph.json pqp22.graph.json
mv pqp19.graph.json pqp21.graph.json
mv pqp18.graph.json pqp20.graph.json
mv pqp17.graph.json pqp19.graph.json
mv pqp16.graph.json pqp18.graph.json
mv pqp15.graph.json pqp17.graph.json
mv pqp14.graph.json pqp16.graph.json
mv pqp13.graph.json pqp14.graph.json
mv pqp12.graph.json pqp13.graph.json
mv pqp11.graph.json pqp12.graph.json
mv pqp10.graph.json pqp11.graph.json
mv pqp9.graph.json pqp10.graph.json
mv pqp8.graph.json pqp9.graph.json
mv pqp7.graph.json pqp8.graph.json
mv pqp6.graph.json pqp7.graph.json
mv pqp5.graph.json pqp6.graph.json
mv pqp4.graph.json pqp5.graph.json
mv pqp3.graph.json pqp4.graph.json
mv pqp2.graph.json pqp3.graph.json
mv pqp1.graph.json pqp2.graph.json
mv pqp0.graph.json pqp1.graph.json