setting print off
setting binary_caching on
setting workers 16
generate_tpch 100
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/move_all_cols_to_remote.sql
hsh mem_usage
hsh new_mem 107374182400 0 2
hsh new_mem 107374182400 1 3
hsh mem_usage
setting workers 8
setting mem_strategy Greedy
setting label d26843545600_tf5368709120_q091
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/mapping/lqp/map_d26843545600_f20_q091_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/091.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/091.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/091.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/091.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/091.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf5368709120_q092
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/mapping/lqp/map_d26843545600_f20_q092_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/092.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/092.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/092.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/092.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/092.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf5368709120_q094
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/mapping/lqp/map_d26843545600_f20_q094_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/094.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/094.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/094.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/094.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/094.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf5368709120_q095
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/mapping/lqp/map_d26843545600_f20_q095_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/095.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/095.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/095.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/095.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/095.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf2684354560_q131
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/mapping/lqp/map_d26843545600_f10_q131_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/131.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/131.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/131.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/131.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/131.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf2684354560_q132
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/mapping/lqp/map_d26843545600_f10_q132_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/132.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/132.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/132.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/132.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/132.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf2684354560_q133
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/mapping/lqp/map_d26843545600_f10_q133_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/133.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/133.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/133.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/133.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/133.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf2684354560_q134
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/mapping/lqp/map_d26843545600_f10_q134_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/134.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/134.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/134.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/134.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/134.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf2684354560_q135
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/mapping/lqp/map_d26843545600_f10_q135_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/135.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/135.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/135.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/135.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/135.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf10737418240_q213
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/mapping/lqp/map_d26843545600_f40_q213_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/213.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/213.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/213.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/213.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/213.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
quit
