setting print off
setting binary_caching on
setting workers 16
generate_tpch 50
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/move_all_cols_to_remote.sql
hsh mem_usage
hsh new_mem 60000000000 0 2
hsh new_mem 60000000000 1 3
hsh mem_usage
setting workers 8
setting mem_strategy Greedy
hsh set_mem_capacity 60000000000 1000000000000
setting label d0_tf0_q1
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/1.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/1.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/1.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/1.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/1.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q2
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/2.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/2.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/2.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/2.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/2.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q3
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/3.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/3.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/3.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/3.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/3.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q4
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/4.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/4.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/4.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/4.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/4.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q5
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/5.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/5.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/5.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/5.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/5.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q6
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/6.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/6.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/6.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/6.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/microbenchmark/6.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
quit