setting workers 8
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/091.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/092.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/093.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/094.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/095.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/131.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/132.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/133.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/134.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/135.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/211.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/212.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/213.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/214.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/hyrise_pmr/myscripts/tree_similarity/queries/215.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
quit