setting print off
setting binary_caching on
setting workers 16
generate_tpch 100
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/move_all_cols_to_remote.sql
hsh mem_usage
hsh new_mem 107374182400 0 2
hsh new_mem 107374182400 1 3
hsh mem_usage
setting workers 8
setting mem_strategy Greedy
setting label d26843545600_tf2684354560_q10
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f10_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf2684354560_q18
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f10_q18_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf2684354560_q19
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f10_q19_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf2684354560_q20
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f10_q20_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf2684354560_q2
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f10_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf2684354560_q5
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f10_q5_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf2684354560_q8
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f10_q8_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/8.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/8.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/8.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/8.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/8.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf2684354560_q9
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f10_q9_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf5368709120_q10
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f20_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf5368709120_q18
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f20_q18_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf5368709120_q19
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f20_q19_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf5368709120_q20
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f20_q20_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf5368709120_q2
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f20_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf5368709120_q3
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f20_q3_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf5368709120_q4
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f20_q4_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/4.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/4.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/4.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/4.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/4.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf5368709120_q5
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f20_q5_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf5368709120_q7
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f20_q7_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/7.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/7.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/7.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/7.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/7.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf5368709120_q9
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f20_q9_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf8053063680_q10
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f30_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf8053063680_q12
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f30_q12_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/12.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/12.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/12.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/12.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/12.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf8053063680_q14
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f30_q14_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/14.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/14.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/14.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/14.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/14.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf8053063680_q18
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f30_q18_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf8053063680_q19
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f30_q19_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf8053063680_q20
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f30_q20_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf8053063680_q2
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f30_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf8053063680_q5
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f30_q5_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf8053063680_q8
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f30_q8_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/8.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/8.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/8.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/8.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/8.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf8053063680_q9
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f30_q9_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf10737418240_q10
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f40_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf10737418240_q18
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f40_q18_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf10737418240_q19
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f40_q19_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf10737418240_q20
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f40_q20_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf10737418240_q2
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f40_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf10737418240_q5
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f40_q5_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf10737418240_q8
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f40_q8_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/8.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/8.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/8.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/8.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/8.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf10737418240_q9
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f40_q9_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf13421772800_q10
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f50_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf13421772800_q18
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f50_q18_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf13421772800_q19
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f50_q19_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf13421772800_q20
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f50_q20_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf13421772800_q2
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f50_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf13421772800_q5
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f50_q5_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf13421772800_q8
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f50_q8_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/8.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/8.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/8.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/8.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/8.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf13421772800_q9
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f50_q9_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf16106127360_q10
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f60_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf16106127360_q18
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f60_q18_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf16106127360_q19
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f60_q19_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf16106127360_q20
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f60_q20_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf16106127360_q2
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f60_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf16106127360_q5
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f60_q5_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf18790481920_q10
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f70_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf18790481920_q18
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f70_q18_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf18790481920_q19
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f70_q19_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf18790481920_q20
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f70_q20_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf18790481920_q2
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f70_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf18790481920_q5
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f70_q5_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf21474836480_q10
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f80_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf21474836480_q18
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f80_q18_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf21474836480_q19
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f80_q19_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf21474836480_q20
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f80_q20_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf21474836480_q2
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f80_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf21474836480_q5
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f80_q5_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf24159191040_q10
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f90_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf24159191040_q18
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f90_q18_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf24159191040_q19
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f90_q19_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf24159191040_q20
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f90_q20_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf24159191040_q2
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f90_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d26843545600_tf24159191040_q5
hsh set_mem_capacity 26843545600 1000000000000
script /home/umeshsum/hyrise_pmr/myscripts/mapping/scratch/sf100/lqp/map_d26843545600_f90_q5_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
quit
