move2cxl lineitem l_shipmode 0
move2cxl orders o_orderkey 0
move2cxl orders o_orderpriority 0
move2cxl lineitem l_orderkey 0
move2cxl lineitem l_receiptdate 0
move2cxl lineitem l_shipdate 0
move2cxl lineitem l_commitdate 0
move2cxl part p_name 1
move2cxl orders o_comment 1
move2cxl partsupp ps_suppkey 1
move2cxl nation n_regionkey 1
move2cxl part p_partkey 1
move2cxl customer c_nationkey 1
move2cxl lineitem l_quantity 1
move2cxl customer c_name 1
move2cxl orders o_shippriority 1
move2cxl lineitem l_comment 1
move2cxl nation n_name 1
move2cxl customer c_custkey 1
move2cxl lineitem l_returnflag 1
move2cxl partsupp ps_availqty 1
move2cxl partsupp ps_comment 1
move2cxl lineitem l_discount 1
move2cxl supplier s_suppkey 1
move2cxl orders o_orderdate 1
move2cxl supplier s_nationkey 1
move2cxl supplier s_phone 1
move2cxl nation n_comment 1
move2cxl lineitem l_shipinstruct 1
move2cxl supplier s_comment 1
move2cxl part p_size 1
move2cxl part p_container 1
move2cxl part p_mfgr 1
move2cxl nation n_nationkey 1
move2cxl part p_comment 1
move2cxl lineitem l_linestatus 1
move2cxl orders o_orderstatus 1
move2cxl lineitem l_suppkey 1
move2cxl supplier s_name 1
move2cxl customer c_phone 1
move2cxl customer c_mktsegment 1
move2cxl orders o_totalprice 1
move2cxl part p_type 1
move2cxl part p_retailprice 1
move2cxl partsupp ps_supplycost 1
move2cxl region r_name 1
move2cxl lineitem l_linenumber 1
move2cxl region r_regionkey 1
move2cxl supplier s_address 1
move2cxl supplier s_acctbal 1
move2cxl customer c_comment 1
move2cxl partsupp ps_partkey 1
move2cxl customer c_address 1
move2cxl customer c_acctbal 1
move2cxl lineitem l_tax 1
move2cxl region r_comment 1
move2cxl lineitem l_partkey 1
move2cxl orders o_clerk 1
move2cxl part p_brand 1
move2cxl orders o_custkey 1
move2cxl lineitem l_extendedprice 1
