setting print off
setting workers 16
setting binary_caching on
generate_tpch 100
setting workers 8
hsh new_mem 70000000000 1 3
hsh set_mem_capacity 70000000000 100000000000
setting mem_strategy Remote
setting track_peak on
script /home/umeshsum/tpch_queries/1.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/2.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/3.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/4.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/5.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/6.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/7.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/8.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/9.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/10.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/11.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/12.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/13.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/14.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/16.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/17.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/18.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/19.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/20.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/21.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /home/umeshsum/tpch_queries/22.sql
visualize lqp
visualize pqp
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
quit
