setting print off
setting workers 16
setting binary_caching on
generate_tpch 10
setting workers 8
script /data1/sumanthu/tpch_queries/1.sql
visualize lqp
visualize pqp
script /data1/sumanthu/tpch_queries/2.sql
visualize lqp
visualize pqp
script /data1/sumanthu/tpch_queries/3.sql
visualize lqp
visualize pqp
script /data1/sumanthu/tpch_queries/4.sql
visualize lqp
visualize pqp
script /data1/sumanthu/tpch_queries/5.sql
visualize lqp
visualize pqp
script /data1/sumanthu/tpch_queries/6.sql
visualize lqp
visualize pqp
script /data1/sumanthu/tpch_queries/7.sql
visualize lqp
visualize pqp
script /data1/sumanthu/tpch_queries/8.sql
visualize lqp
visualize pqp
script /data1/sumanthu/tpch_queries/9.sql
visualize lqp
visualize pqp
script /data1/sumanthu/tpch_queries/10.sql
visualize lqp
visualize pqp
script /data1/sumanthu/tpch_queries/11.sql
visualize lqp
visualize pqp
script /data1/sumanthu/tpch_queries/12.sql
visualize lqp
visualize pqp
script /data1/sumanthu/tpch_queries/13.sql
visualize lqp
visualize pqp
script /data1/sumanthu/tpch_queries/14.sql
visualize lqp
visualize pqp
script /data1/sumanthu/tpch_queries/16.sql
visualize lqp
visualize pqp
script /data1/sumanthu/tpch_queries/17.sql
visualize lqp
visualize pqp
script /data1/sumanthu/tpch_queries/18.sql
visualize lqp
visualize pqp
script /data1/sumanthu/tpch_queries/19.sql
visualize lqp
visualize pqp
script /data1/sumanthu/tpch_queries/20.sql
visualize lqp
visualize pqp
script /data1/sumanthu/tpch_queries/21.sql
visualize lqp
visualize pqp
script /data1/sumanthu/tpch_queries/22.sql
visualize lqp
visualize pqp
quit
