tpch_table_column_names = [("supplier","s_comment"),
("supplier","s_acctbal"),
("orders","o_orderkey"),
("customer","c_acctbal"),
("nation","n_regionkey"),
("lineitem","l_comment"),
("nation","n_name"),
("lineitem","l_shipmode"),
("supplier","s_phone"),
("nation","n_nationkey"),
("lineitem","l_shipinstruct"),
("part","p_comment"),
("supplier","s_nationkey"),
("lineitem","l_receiptdate"),
("part","p_retailprice"),
("supplier","s_address"),
("lineitem","l_commitdate"),
("part","p_container"),
("supplier","s_name"),
("lineitem","l_shipdate"),
("part","p_size"),
("supplier","s_suppkey"),
("lineitem","l_linestatus"),
("part","p_type"),
("lineitem","l_returnflag"),
("part","p_brand"),
("lineitem","l_tax"),
("part","p_mfgr"),
("lineitem","l_discount"),
("part","p_name"),
("lineitem","l_extendedprice"),
("part","p_partkey"),
("nation","n_comment"),
("customer","c_custkey"),
("lineitem","l_quantity"),
("customer","c_name"),
("customer","c_address"),
("customer","c_nationkey"),
("customer","c_phone"),
("customer","c_mktsegment"),
("orders","o_custkey"),
("customer","c_comment"),
("orders","o_orderstatus"),
("lineitem","l_orderkey"),
("lineitem","l_partkey"),
("lineitem","l_suppkey"),
("lineitem","l_linenumber"),
("orders","o_totalprice"),
("orders","o_orderdate"),
("orders","o_orderpriority"),
("region","r_regionkey"),
("orders","o_clerk"),
("region","r_name"),
("orders","o_shippriority"),
("region","r_comment"),
("orders","o_comment"),
("partsupp","ps_partkey"),
("partsupp","ps_suppkey"),
("partsupp","ps_availqty"),
("partsupp","ps_supplycost"),
("partsupp","ps_comment")]

# (table, column, hyrise_datatype)
# Hyrise types: Int (int32), Long (int64), Float, Double, String (pmr_string)
tpch_table_column_types = [
    ("supplier",  "s_suppkey",      "Int"),
    ("supplier",  "s_name",         "String"),
    ("supplier",  "s_address",      "String"),
    ("supplier",  "s_nationkey",    "Int"),
    ("supplier",  "s_phone",        "String"),
    ("supplier",  "s_acctbal",      "Double"),
    ("supplier",  "s_comment",      "String"),
    ("part",      "p_partkey",      "Int"),
    ("part",      "p_name",         "String"),
    ("part",      "p_mfgr",         "String"),
    ("part",      "p_brand",        "String"),
    ("part",      "p_type",         "String"),
    ("part",      "p_size",         "Int"),
    ("part",      "p_container",    "String"),
    ("part",      "p_retailprice",  "Double"),
    ("part",      "p_comment",      "String"),
    ("partsupp",  "ps_partkey",     "Int"),
    ("partsupp",  "ps_suppkey",     "Int"),
    ("partsupp",  "ps_availqty",    "Int"),
    ("partsupp",  "ps_supplycost",  "Double"),
    ("partsupp",  "ps_comment",     "String"),
    ("customer",  "c_custkey",      "Int"),
    ("customer",  "c_name",         "String"),
    ("customer",  "c_address",      "String"),
    ("customer",  "c_nationkey",    "Int"),
    ("customer",  "c_phone",        "String"),
    ("customer",  "c_acctbal",      "Double"),
    ("customer",  "c_mktsegment",   "String"),
    ("customer",  "c_comment",      "String"),
    ("orders",    "o_orderkey",     "Int"),
    ("orders",    "o_custkey",      "Int"),
    ("orders",    "o_orderstatus",  "String"),
    ("orders",    "o_totalprice",   "Double"),
    ("orders",    "o_orderdate",    "String"),
    ("orders",    "o_orderpriority","String"),
    ("orders",    "o_clerk",        "String"),
    ("orders",    "o_shippriority", "Int"),
    ("orders",    "o_comment",      "String"),
    ("lineitem",  "l_orderkey",     "Int"),
    ("lineitem",  "l_partkey",      "Int"),
    ("lineitem",  "l_suppkey",      "Int"),
    ("lineitem",  "l_linenumber",   "Int"),
    ("lineitem",  "l_quantity",     "Double"),
    ("lineitem",  "l_extendedprice","Double"),
    ("lineitem",  "l_discount",     "Double"),
    ("lineitem",  "l_tax",          "Double"),
    ("lineitem",  "l_returnflag",   "String"),
    ("lineitem",  "l_linestatus",   "String"),
    ("lineitem",  "l_shipdate",     "String"),
    ("lineitem",  "l_commitdate",   "String"),
    ("lineitem",  "l_receiptdate",  "String"),
    ("lineitem",  "l_shipinstruct", "String"),
    ("lineitem",  "l_shipmode",     "String"),
    ("lineitem",  "l_comment",      "String"),
    ("nation",    "n_nationkey",    "Int"),
    ("nation",    "n_name",         "String"),
    ("nation",    "n_regionkey",    "Int"),
    ("nation",    "n_comment",      "String"),
    ("region",    "r_regionkey",    "Int"),
    ("region",    "r_name",         "String"),
    ("region",    "r_comment",      "String"),
]

# Quick lookup: (table, column) -> hyrise_datatype
tpch_column_type = {(t, c): dt for t, c, dt in tpch_table_column_types}