setting print off
setting binary_caching on
setting workers 16
generate_tpch 1
hsh mem_usage
script /data1/sumanthu/hyrise_pmr/myscripts/move_all_cols_to_remote.sql
hsh mem_usage
hsh new_mem 53687091200 0 2
hsh new_mem 53687091200 1 3
hsh mem_usage
setting workers 8
setting mem_strategy Greedy
setting label d10737418240_tf1073741824_q10
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f10_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d10737418240_tf1073741824_q2
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f10_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d10737418240_tf1073741824_q3
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f10_q3_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d10737418240_tf1073741824_q5
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f10_q5_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d10737418240_tf2147483648_q10
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f20_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d10737418240_tf2147483648_q21
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f20_q21_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/21.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/21.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/21.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/21.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/21.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d10737418240_tf2147483648_q2
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f20_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d10737418240_tf2147483648_q9
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f20_q9_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d10737418240_tf3221225472_q10
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f30_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d10737418240_tf3221225472_q18
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f30_q18_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d10737418240_tf3221225472_q2
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f30_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d10737418240_tf4294967296_q10
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f40_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d10737418240_tf4294967296_q14
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f40_q14_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/14.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/14.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/14.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/14.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/14.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d10737418240_tf4294967296_q18
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f40_q18_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d10737418240_tf4294967296_q1
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f40_q1_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d10737418240_tf4294967296_q20
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f40_q20_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d10737418240_tf4294967296_q2
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f40_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d10737418240_tf4294967296_q9
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f40_q9_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d10737418240_tf5368709120_q10
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f50_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d10737418240_tf5368709120_q18
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f50_q18_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d10737418240_tf5368709120_q20
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f50_q20_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d10737418240_tf5368709120_q2
hsh set_mem_capacity 10737418240 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d10737418240_f50_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf1342177280_q10
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f10_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf1342177280_q1
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f10_q1_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf1342177280_q2
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f10_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf1342177280_q3
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f10_q3_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf2684354560_q10
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f20_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf2684354560_q18
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f20_q18_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf2684354560_q2
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f20_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf2684354560_q4
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f20_q4_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/4.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/4.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/4.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/4.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/4.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf2684354560_q5
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f20_q5_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf4026531840_q10
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f30_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf4026531840_q14
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f30_q14_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/14.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/14.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/14.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/14.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/14.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf4026531840_q18
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f30_q18_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf4026531840_q21
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f30_q21_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/21.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/21.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/21.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/21.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/21.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf4026531840_q2
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f30_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf5368709120_q10
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f40_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf5368709120_q18
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f40_q18_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf5368709120_q20
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f40_q20_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf5368709120_q2
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f40_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf6710886400_q10
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f50_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf6710886400_q18
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f50_q18_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf6710886400_q20
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f50_q20_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d13421772800_tf6710886400_q2
hsh set_mem_capacity 13421772800 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d13421772800_f50_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d2684354560_tf268435456_q10
hsh set_mem_capacity 2684354560 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d2684354560_f10_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d2684354560_tf268435456_q2
hsh set_mem_capacity 2684354560 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d2684354560_f10_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d2684354560_tf268435456_q9
hsh set_mem_capacity 2684354560 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d2684354560_f10_q9_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d2684354560_tf536870912_q10
hsh set_mem_capacity 2684354560 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d2684354560_f20_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d2684354560_tf536870912_q13
hsh set_mem_capacity 2684354560 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d2684354560_f20_q13_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/13.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/13.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/13.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/13.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/13.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d2684354560_tf536870912_q1
hsh set_mem_capacity 2684354560 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d2684354560_f20_q1_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d2684354560_tf536870912_q2
hsh set_mem_capacity 2684354560 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d2684354560_f20_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d2684354560_tf805306368_q10
hsh set_mem_capacity 2684354560 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d2684354560_f30_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d2684354560_tf805306368_q22
hsh set_mem_capacity 2684354560 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d2684354560_f30_q22_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/22.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/22.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/22.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/22.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/22.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d2684354560_tf805306368_q2
hsh set_mem_capacity 2684354560 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d2684354560_f30_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d2684354560_tf1073741824_q10
hsh set_mem_capacity 2684354560 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d2684354560_f40_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d2684354560_tf1073741824_q2
hsh set_mem_capacity 2684354560 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d2684354560_f40_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d2684354560_tf1073741824_q3
hsh set_mem_capacity 2684354560 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d2684354560_f40_q3_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d2684354560_tf1073741824_q5
hsh set_mem_capacity 2684354560 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d2684354560_f40_q5_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d2684354560_tf1342177280_q10
hsh set_mem_capacity 2684354560 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d2684354560_f50_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d2684354560_tf1342177280_q1
hsh set_mem_capacity 2684354560 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d2684354560_f50_q1_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d2684354560_tf1342177280_q2
hsh set_mem_capacity 2684354560 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d2684354560_f50_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d2684354560_tf1342177280_q3
hsh set_mem_capacity 2684354560 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d2684354560_f50_q3_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d5368709120_tf536870912_q10
hsh set_mem_capacity 5368709120 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d5368709120_f10_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d5368709120_tf536870912_q13
hsh set_mem_capacity 5368709120 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d5368709120_f10_q13_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/13.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/13.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/13.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/13.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/13.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d5368709120_tf536870912_q1
hsh set_mem_capacity 5368709120 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d5368709120_f10_q1_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d5368709120_tf536870912_q2
hsh set_mem_capacity 5368709120 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d5368709120_f10_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d5368709120_tf1073741824_q10
hsh set_mem_capacity 5368709120 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d5368709120_f20_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d5368709120_tf1073741824_q2
hsh set_mem_capacity 5368709120 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d5368709120_f20_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d5368709120_tf1073741824_q3
hsh set_mem_capacity 5368709120 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d5368709120_f20_q3_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d5368709120_tf1073741824_q5
hsh set_mem_capacity 5368709120 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d5368709120_f20_q5_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d5368709120_tf1610612736_q10
hsh set_mem_capacity 5368709120 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d5368709120_f30_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d5368709120_tf1610612736_q2
hsh set_mem_capacity 5368709120 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d5368709120_f30_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d5368709120_tf1610612736_q3
hsh set_mem_capacity 5368709120 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d5368709120_f30_q3_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d5368709120_tf2147483648_q10
hsh set_mem_capacity 5368709120 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d5368709120_f40_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d5368709120_tf2147483648_q21
hsh set_mem_capacity 5368709120 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d5368709120_f40_q21_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/21.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/21.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/21.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/21.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/21.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d5368709120_tf2147483648_q2
hsh set_mem_capacity 5368709120 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d5368709120_f40_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d5368709120_tf2147483648_q9
hsh set_mem_capacity 5368709120 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d5368709120_f40_q9_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d5368709120_tf2684354560_q10
hsh set_mem_capacity 5368709120 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d5368709120_f50_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d5368709120_tf2684354560_q18
hsh set_mem_capacity 5368709120 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d5368709120_f50_q18_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d5368709120_tf2684354560_q2
hsh set_mem_capacity 5368709120 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d5368709120_f50_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d5368709120_tf2684354560_q4
hsh set_mem_capacity 5368709120 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d5368709120_f50_q4_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/4.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/4.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/4.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/4.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/4.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d5368709120_tf2684354560_q5
hsh set_mem_capacity 5368709120 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d5368709120_f50_q5_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/5.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d8053063680_tf805306368_q10
hsh set_mem_capacity 8053063680 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d8053063680_f10_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d8053063680_tf805306368_q22
hsh set_mem_capacity 8053063680 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d8053063680_f10_q22_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/22.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/22.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/22.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/22.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/22.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d8053063680_tf805306368_q2
hsh set_mem_capacity 8053063680 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d8053063680_f10_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d8053063680_tf1610612736_q10
hsh set_mem_capacity 8053063680 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d8053063680_f20_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d8053063680_tf1610612736_q2
hsh set_mem_capacity 8053063680 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d8053063680_f20_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d8053063680_tf1610612736_q3
hsh set_mem_capacity 8053063680 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d8053063680_f20_q3_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/3.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d8053063680_tf2415919104_q10
hsh set_mem_capacity 8053063680 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d8053063680_f30_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d8053063680_tf2415919104_q18
hsh set_mem_capacity 8053063680 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d8053063680_f30_q18_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d8053063680_tf2415919104_q1
hsh set_mem_capacity 8053063680 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d8053063680_f30_q1_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/1.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d8053063680_tf2415919104_q20
hsh set_mem_capacity 8053063680 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d8053063680_f30_q20_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/20.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d8053063680_tf2415919104_q2
hsh set_mem_capacity 8053063680 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d8053063680_f30_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d8053063680_tf2415919104_q9
hsh set_mem_capacity 8053063680 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d8053063680_f30_q9_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/9.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d8053063680_tf3221225472_q10
hsh set_mem_capacity 8053063680 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d8053063680_f40_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d8053063680_tf3221225472_q18
hsh set_mem_capacity 8053063680 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d8053063680_f40_q18_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d8053063680_tf3221225472_q2
hsh set_mem_capacity 8053063680 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d8053063680_f40_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d8053063680_tf4026531840_q10
hsh set_mem_capacity 8053063680 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d8053063680_f50_q10_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/10.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d8053063680_tf4026531840_q14
hsh set_mem_capacity 8053063680 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d8053063680_f50_q14_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/14.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/14.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/14.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/14.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/14.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d8053063680_tf4026531840_q18
hsh set_mem_capacity 8053063680 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d8053063680_f50_q18_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/18.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d8053063680_tf4026531840_q21
hsh set_mem_capacity 8053063680 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d8053063680_f50_q21_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/21.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/21.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/21.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/21.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/21.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
setting label d8053063680_tf4026531840_q2
hsh set_mem_capacity 8053063680 1000000000000
script /data1/sumanthu/hyrise_pmr/myscripts/mapping/scratch/sf50_pqp/map_d8053063680_f50_q2_migrate.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
script /data1/sumanthu/tpch_queries/2.sql
hsh mem_usage
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
quit
