setting print off
setting binary_caching on
setting workers 16
generate_tpch 50
hsh mem_usage
script /home/umeshsum/hyrise_pmr/myscripts/all_cols_to_remote.sql
hsh mem_usage
setting workers 8
setting label d0_tf0_q10
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/10.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/10.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/10.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/10.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/10.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/10.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/10.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/10.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/10.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/10.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q11
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/11.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/11.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/11.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/11.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/11.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/11.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/11.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/11.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/11.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/11.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/11.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q12
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/12.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/12.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/12.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/12.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/12.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/12.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/12.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/12.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/12.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/12.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/12.sql
hsh mem_usage
setting label d0_tf0_q13
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/13.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/13.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/13.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/13.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/13.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/13.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/13.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/13.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/13.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/13.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q14
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/14.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/14.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/14.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/14.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/14.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/14.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/14.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/14.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/14.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/14.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q16
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/16.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/16.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/16.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/16.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/16.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/16.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/16.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/16.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/16.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/16.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q17
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/17.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/17.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/17.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/17.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/17.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/17.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/17.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/17.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/17.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/17.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q18
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/18.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/18.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/18.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/18.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/18.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/18.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/18.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/18.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/18.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/18.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q19
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/19.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/19.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/19.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/19.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/19.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/19.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/19.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/19.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/19.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/19.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q1
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/1.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/1.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/1.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/1.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/1.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/1.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/1.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/1.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/1.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/1.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q20
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/20.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/20.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/20.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/20.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/20.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/20.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/20.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/20.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/20.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/20.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q21
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/21.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/21.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/21.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/21.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/21.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/21.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/21.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/21.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/21.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/21.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q22
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/22.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/22.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/22.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/22.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/22.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/22.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/22.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/22.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/22.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/22.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q2
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/2.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/2.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/2.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/2.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/2.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/2.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/2.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/2.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/2.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/2.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q3
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/3.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/3.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/3.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/3.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/3.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/3.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/3.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/3.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/3.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/3.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q4
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/4.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/4.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/4.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/4.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/4.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/4.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/4.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/4.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/4.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/4.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q5
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/5.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/5.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/5.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/5.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/5.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/5.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/5.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/5.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/5.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/5.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q6
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/6.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/6.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/6.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/6.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/6.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/6.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/6.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/6.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/6.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/6.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q7
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/7.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/7.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/7.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/7.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/7.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/7.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/7.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/7.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/7.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/7.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q8
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/8.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/8.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/8.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/8.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/8.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/8.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/8.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/8.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/8.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/8.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
setting label d0_tf0_q9
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/9.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/9.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/9.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/9.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/9.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/9.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/9.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/9.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/9.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
script /home/umeshsum/tpch_queries/9.sql
hsh clear_plan_caches
hsh clear_pipeline
hsh reset_exec_pools
hsh mem_usage
quit
