setting workers 8
setting label d0_tf0_q9
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
script /home/umeshsum/tpch_queries/9.sql
quit
